version: "3.8"

services:
  app:
    build: .
    container_name: hoangtu-chatbot
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-hoangtu_chatbot}
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
    networks:
      - frontend # cho web traffic
      - backend # cho database traffic
      - milvus # cho vector database traffic
    volumes:
      - .:/app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: hoangtu-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-hoangtu_chatbot}
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    networks:
      - backend # chỉ cần kết nối với backend
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

networks:
  frontend:
    name: hoangtu_frontend
    driver: bridge
  backend:
    name: hoangtu_backend
    driver: bridge
    internal: true # network này chỉ dùng nội bộ, không thể truy cập từ bên ngoài
  milvus:
    external: true # sử dụng milvus network đã tồn tại

volumes:
  mysql_data:
